In [2]:
import numpy as np
arr_2d =([[1,4,3],[4,2,3],[1,2,4]])
print(arr_2d)
uni=np.unique(arr_2d)
print(uni)

[[1, 4, 3], [4, 2, 3], [1, 2, 4]]
[1 2 3 4]


In [2]:
import numpy as np
array=np.zeros((2,3))
print(array)
array=np.ones((2,3))
print(array)
arr1=np.linspace(0,6,3)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0. 3. 6.]


In [4]:
import numpy as np
arr=np.arange(21)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
import numpy as np
array=np.arange(36).reshape(3,3,4)
print(array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [25]:
arr=np.arange(36).reshape(3,4,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [27]:
array_1D=np.arange(24)
reshape=array_1D.reshape(2,3,4)
print(reshape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [29]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
array=np.add(arr1,arr2)
print(array)

[5 7 9]


In [35]:
arr=np.array([[1,4,3],
              [4,2,3],
              [1,2,4]])
print(arr[0:2,0:2])
arr[0:2,0:2]=0
print(arr)

[[1 4]
 [4 2]]
[[0 0 3]
 [0 0 3]
 [1 2 4]]
