In [16]:
import numpy as np
import array as arr

l1=[1,2,3,4,"Manish",5,6,9,8,7]
l1.append(12)
print(l1)

[1, 2, 3, 4, 'Manish', 5, 6, 9, 8, 7, 12]


In [12]:
arr1=arr.array('i',[1,2,3,6,5,4])
print(arr1)

array('i', [1, 2, 3, 6, 5, 4])


In [18]:
arr=np.array([1,2,3,6,5,4],int)
print(arr*2)
print(arr+5)

[ 2  4  6 12 10  8]
[ 6  7  8 11 10  9]


In [24]:
#####  ================= 1D array  ==================

import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6])
sum = np.sum(arr1)
print(sum)

21


In [43]:
#####  ================= 2D array  ==================

import numpy as np
import array as arr
array_2d=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]]) 
print(array_2d)
#print(array_2d[1,2])
print(array_2d[2,2])
print(array_2d.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)


In [97]:
#########===========  Slicing ==========

array_2d=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [7,23,15]]) 
print(array_2d[:,1])  #col
print("-----------------------------------")
print(array_2d[0,:])  #row
print("------------------------------------")
print(array_2d[:])
print("-----------------------------------")
# print(array_2d[::3,:])
print(array_2d[::2,::2])
print("-----------------------------------")
print(array_2d[:,-1])
print("-----------------------------------")
print(array_2d.shape)
print("-----------------------------------")
# reshape=array_2d.reshape(3,12)
# reshape=array_2d.reshape(3,4)
# reshape=array_2d.reshape(4,4)
# print(reshape)
print(len(array_2d)) 
print("-----------------------------------")
# print(len(array_2d[3]))

row_len=len(array_2d)
col_len=len(array_2d[3])
print(row_len-1,col_len-1)
print("------------------------------------")
print(array_2d[0,0]+array_2d[row_len-1,col_len-1])


[ 2  5  8 23]
-----------------------------------
[1 2 3]
------------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 7 23 15]]
-----------------------------------
[[1 3]
 [7 9]]
-----------------------------------
[ 3  6  9 15]
-----------------------------------
(4, 3)
-----------------------------------
4
-----------------------------------
3 2
------------------------------------
16


In [99]:
arr_3d=np.array([[[1,2,3],
                  [4,5,6],
                  [8,9,7],
                  [7,8,9],
                  [78,89,45],
                  [54,65,21]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9  7]
  [ 7  8  9]
  [78 89 45]
  [54 65 21]]]
3
(1, 6, 3)


In [101]:
arr_3d=np.array([[[1,2,3],[4,5,6],[8,9,7]],
                 [[7,8,9],[78,89,45],[54,65,21]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9  7]]

 [[ 7  8  9]
  [78 89 45]
  [54 65 21]]]
3
(2, 3, 3)
